name: visionary_ai_mobile 
description: AI-powered personal scheduler mobile app 
version: 1.0.0+1 
 
environment: 
 
dependencies: 
  flutter: 
    sdk: flutter 
  http: 1.1.0 
  dio: 5.3.2 
  provider: 6.0.5 
  go_router: 12.1.1 
  file_picker: 6.1.1 
  image_picker: 1.0.4 
  shared_preferences: 2.2.2 
  path_provider: 2.1.1 
 
dev_dependencies: 
  flutter_test: 
    sdk: flutter 
  flutter_lints: 3.0.0 
 
flutter: 
  uses-material-design: true 
